### ISSUE TITLE
Hello, is this project dead?

### ISSUE THREAD

**Issue by gespi1** [muhammadn/jaeger-tempo#14]
its in the title. Is flitnetics still using this plugin to this day?

**Comment by muhammadn** [comment]
@gespi1 This plugin is a fork of the original code from grafana (which they no longer maintain). Do you have problems using this plugin? No, the project is not dead. I'm still building it here.

**Comment by muhammadn** [comment]
@gespi1 The work is now at [jaeger-objectstorage](https://github.com/flitnetics/jaeger-objectstorage) repository. We have switch to use tempo backend instead of loki in `jaeger-objectstorage` so you should take a look there instead.

More info in the annoucement here: https://community.flitnetics.com/t/upcoming-update-of-jaeger-objectstorage/9/4

I'm going to close this and this repo will be archived, so please take a look at `jaeger-objectstorage`
